Repository Unionstation-13/Unionstation13, pull requests merged in 2025-04, with the labels that each got.

#13 Final Job Pull
  code/datums/outfits/jobs/engineering.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/engineering.dm
  code/modules/mob/living/carbon/human/corpse.dm
  maps/torch/icons/assignment_hud.dmi
  maps/torch/job/command_jobs.dm
  maps/torch/job/exploration_jobs.dm
  maps/torch/job/medical_jobs.dm
  maps/torch/job/security_jobs.dm
  maps/torch/job/supply_jobs.dm
Labels: enhancement

#27 Expands current faction-based whitelist/blacklist system
  code/modules/culture_descriptor/faction/_faction.dm
  code/modules/culture_descriptor/faction/factions_human.dm
  code/modules/species/species_helpers.dm
  maps/mapsystem/maps_jobs.dm
  maps/torch/icons/assignment_hud.dmi
Labels: documentation, refactor

#33 Changing manuals
  code/__defines/culture.dm
  code/modules/culture_descriptor/faction/factions_human.dm
  code/modules/species/station/station.dm
  maps/mapsystem/maps.dm
  maps/mapsystem/maps_jobs.dm
  maps/torch/icons/assignment_hud.dmi
  maps/torch/items/clothing/solgov-accessory.dm
  maps/torch/items/manuals.dm
  packs/event_2022jul30/documents.dm
Labels: enhancement, help wanted
